** Settings **
Library  SeleniumLibrary

** Variables **

#Elements da Home Page
${input_email}                  //*[@id="__next"]/div/section[1]/div/div/div[1]/form/div[1]/input
${input_senha}                  //*[@id="__next"]/div/section[1]/div/div/div[1]/form/div[2]/input
${button_entrar}                //*[@id="__next"]/div/section[1]/div/div/div[1]/form/div[3]/button[2]
${email_vazio}      
${erro_acesso_email_message}    *E-mail ou senha inválidos